# FlowSDF configuration for flow-matching training

model:
  image_size: 320
  dim: 64
  sigma_min: 0.00001
  ode_steps: 4
  learning_rate: 2e-4
  weight_decay: 1e-5
  experiment_name: flowsdf
  data_name: xca
  use_ema: true
  ema_decay: 0.9999
  thresh: 0.0
  log_image_enabled: true
  log_image_names:
    - '00036.png'
    - '00050.png'
    - '00063.png'
  num_ensemble: 5

data:
  name: xca
  train_dir: data/xca_dataset_split/train
  val_dir: data/xca_dataset_split/val
  test_dir: data/xca_dataset_split/test
  crop_size: 320
  train_bs: 4
  num_samples_per_image: 16

trainer:
  max_epochs: 500
  accelerator: gpu
  devices: 1
  enable_progress_bar: false
  check_val_every_n_epoch: 25
  gradient_clip_val: 1.0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/dice
        mode: max
        save_last: true
        verbose: true
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: xca_flow
      version: flowsdf

